--------------------------------------------------------
--  Arquivo criado - segunda-feira-maio-26-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CARGO_VENCIMENTO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CARGO_VENCIMENTO" 
   (	"ID" NUMBER(38,0), 
	"CARGO_ID" NUMBER, 
	"VENCIMENTO_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CARGO_VENCIMENTO
SET DEFINE OFF;
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('1','1','1');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('2','2','2');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('3','2','9');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('4','2','8');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('5','3','3');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('6','3','9');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('7','3','8');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('8','4','4');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('9','4','9');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('10','4','8');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('11','4','6');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('12','5','5');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('13','5','9');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('14','5','8');
Insert into SYSTEM.CARGO_VENCIMENTO (ID,CARGO_ID,VENCIMENTO_ID) values ('15','5','7');
--------------------------------------------------------
--  DDL for Index PK_CARGO_VENCIMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_CARGO_VENCIMENTO" ON "SYSTEM"."CARGO_VENCIMENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CARGO_VENCIMENTO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CARGO_VENCIMENTO" MODIFY ("CARGO_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CARGO_VENCIMENTO" MODIFY ("VENCIMENTO_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CARGO_VENCIMENTO" ADD CONSTRAINT "PK_CARGO_VENCIMENTO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
